name: Mini DevSecOps Scan

on: [push]

jobs:
  scan-kode:
    runs-on: ubuntu-latest
    steps:
      - name: Hent koden
        uses: actions/checkout@v4

      - name: Scan for hemmeligheder
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./

      - name: Opsæt Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installer dependencies
        run: npm install express

      - name: Scan dependencies (Snyk)
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: SAST scanning (Semgrep)
        run: |
          pip install semgrep
          semgrep --config=p/nodejs-security-audit --error .

      - name: Scan Azure infrastruktur (Checkov)
        uses: bridgecrewio/checkov-action@master
        with:
          file: main.tf
          framework: terraform
          skip_check: CKV2_AZURE_33,CKV2_AZURE_45,CKV2_AZURE_1,CKV2_AZURE_41,CKV2_AZURE_2,CKV2_AZURE_27

      - name: Byg Docker Image
        run: docker build -t test-app:latest .

      - name: Scan container (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'test-app:latest'
          format: 'table'
          severity: 'CRITICAL'
          exit-code: '1'